services:
  _defaults:
    autowire:       true
    autoconfigure:  true
    public:         true

##### Event Subscriber
  Yipikai\LogBundle\EventSubscriber\LogEventSubscriber:
    tags:
      - { name: kernel.event_subscriber }
  yipikai.log.event_subscriber:
    alias:          Yipikai\LogBundle\EventSubscriber\LogEventSubscriber

##### Log Listener
  Yipikai\LogBundle\Listener\CommandListener:
    tags:
      - { name: kernel.event_listener, event: console.command, method: initialize, priority: 2048 }
      - { name: kernel.event_listener, event: console.error, method: error, priority: 2048 }
  yipikai.log.command.listener:
    alias:          Yipikai\LogBundle\Listener\CommandListener

  Yipikai\LogBundle\Listener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: execute, priority: 2048 }
  yipikai.log.execption.listener:
    alis:           Yipikai\LogBundle\Listener\ExceptionListener

  Yipikai\LogBundle\Listener\DoctrineListener:
    tags:
      - { name: doctrine.event_subscriber, connection: default }
  yipikai.log.doctrine.listener:
    alias:          Yipikai\LogBundle\Listener\DoctrineListener

##### Messenger
  Yipikai\LogBundle\Message\LogMessageHandler:  ~
  yipikai.log.message_handler:
    alias:          Yipikai\LogBundle\Message\LogMessageHandler

##### Configuration
  Yipikai\LogBundle\Configuration\LogConfiguration: ~
  yipikai.log.config:
    alias:          Yipikai\LogBundle\Configuration\LogConfiguration

  Yipikai\LogBundle\Services\Log: ~
  yipikai.log:
    alias:          Yipikai\LogBundle\Services\Log